/* 爬山趣 · 山峰数据 */
'use strict';

const MOUNTAINS = [
  {
    id: 'taishan',
    name: '泰山',
    subtitle: '五岳之首 · 帝王封禅之地',
    province: '山东 · 泰安',
    region: '华东',
    elevation: 1545,
    difficulty: 3,
    distance: 9.5,
    duration: '4-6 小时',
    scenery: 4.9,
    bestSeason: '4-6 月、9-11 月',
    tags: ['五岳', '看日出', '文化名山', '夜爬'],
    emoji: '🌄',
    colors: ['#ff9d6e', '#ffe0b0', '#b06a3b', '#7a4629'],
    description: '泰山为五岳之首，素有“天下第一山”之称。从红门出发的经典中路徒步线全程约 9.5 公里，六千余级石阶串联斗母宫、中天门、十八盘，直至南天门与玉皇顶。夜爬泰山等待日出，是无数登山爱好者的启蒙之旅。',
    tips: [
      '山顶温差大，即使夏季也建议带一件外套',
      '夜爬约 22 点从红门出发，日出前抵达日观峰刚刚好',
      '十八盘台阶陡峭，走“之”字形可明显节省体力',
    ],
  },
  {
    id: 'huashan',
    name: '华山',
    subtitle: '奇险天下第一山',
    province: '陕西 · 渭南',
    region: '西北',
    elevation: 2154,
    difficulty: 5,
    distance: 12,
    duration: '6-8 小时（全程徒步）',
    scenery: 4.9,
    bestSeason: '4-6 月、9-10 月',
    tags: ['五岳', '长空栈道', '花岗岩', '险峰'],
    emoji: '🧗',
    colors: ['#8e7cc3', '#d8cff0', '#8a86a8', '#565b73'],
    description: '自古华山一条路。千尺幢、百尺峡、老君犁沟等险段相连，长空栈道悬于垂直崖壁之上，鹞子翻身挑战每一位登山者的胆量。建议西峰索道上、北峰索道下，一日遍览东西南北中五峰。',
    tips: [
      '长空栈道需另购安全绳票，旺季排队较久',
      '雨雾天气部分险段可能临时关闭，出发前查公告',
      '全程攀爬铁索，务必带一副手套',
    ],
  },
  {
    id: 'huangshan',
    name: '黄山',
    subtitle: '五岳归来不看山，黄山归来不看岳',
    province: '安徽 · 黄山市',
    region: '华东',
    elevation: 1864,
    difficulty: 4,
    distance: 14,
    duration: '7-9 小时（两日更佳）',
    scenery: 5.0,
    bestSeason: '3-5 月、9-11 月',
    tags: ['奇松', '云海', '日出', '温泉'],
    emoji: '🌊',
    colors: ['#8fc3dd', '#eaf6fa', '#7fa8b8', '#4f7583'],
    description: '黄山集奇松、怪石、云海、温泉、冬雪五绝于一身。前山雄伟、后山秀丽，迎客松、光明顶、始信峰与西海大峡谷是精华所在。雨后初晴的清晨，站在光明顶看云海翻涌，是黄山给登山者的最高礼遇。',
    tips: [
      '西海大峡谷冬季部分封闭，行前确认开放情况',
      '山顶住宿紧张，看日出需提前预订',
      '云海多出现在雨雪后放晴的清晨，可关注天气预报碰运气',
    ],
  },
  {
    id: 'emeishan',
    name: '峨眉山',
    subtitle: '四大佛教名山之一 · 普贤道场',
    province: '四川 · 乐山',
    region: '西南',
    elevation: 3079,
    difficulty: 4,
    distance: 50,
    duration: '2 天（全程徒步）',
    scenery: 4.8,
    bestSeason: '4-10 月',
    tags: ['佛教名山', '金顶', '猴群', '朝圣'],
    emoji: '🐘',
    colors: ['#f2d488', '#fdf3d0', '#7ba05b', '#4c6f3f'],
    description: '峨眉山是普贤菩萨道场，从报国寺徒步至金顶约需两日，沿途古寺林立、林深雾绕。金顶十方普贤像庄严宏伟，日出、云海、佛光、圣灯并称峨眉四大奇观。',
    tips: [
      '生态猴区注意收好食物和塑料袋，避免被猴群抢夺',
      '山脚到金顶海拔落差近 2600 米，防寒防雨都要准备',
      '体力有限可乘景区大巴至雷洞坪，再步行上金顶',
    ],
  },
  {
    id: 'wugongshan',
    name: '武功山',
    subtitle: '云中草原 · 十万亩高山草甸',
    province: '江西 · 萍乡',
    region: '华东',
    elevation: 1918,
    difficulty: 3,
    distance: 25,
    duration: '2 天（穿越线）',
    scenery: 4.7,
    bestSeason: '5-6 月、9-10 月',
    tags: ['高山草甸', '露营', '星空', '穿越'],
    emoji: '⛺',
    colors: ['#79b4b2', '#dff2ea', '#74b56f', '#4d8b57'],
    description: '武功山以十万亩高山草甸闻名，春夏绿浪翻滚，秋季金黄一片。经典穿越线从沈子村到明月山，绝望坡与发云界是全程精华，山顶星空与日出云海令人难忘，帐篷节已成徒步圈盛事。',
    tips: [
      '山顶风大且无遮挡，帐篷务必选抗风款并打好地钉',
      '穿越线补给点少，需按计划背足水和食物',
      '9-10 月草甸金黄，是一年中最美的季节',
    ],
  },
  {
    id: 'xiangshan',
    name: '香山',
    subtitle: '北京最亲民的赏秋地',
    province: '北京 · 海淀',
    region: '华北',
    elevation: 575,
    difficulty: 1,
    distance: 5,
    duration: '2-3 小时',
    scenery: 4.3,
    bestSeason: '10 月中旬-11 月上旬',
    tags: ['红叶', '亲子', '城市周边'],
    emoji: '🍁',
    colors: ['#f2a65a', '#fbd9b0', '#d1603d', '#96351d'],
    description: '香山公园距北京城区不远，香炉峰海拔虽只有 575 米，视野却极佳。每年 10 月中旬至 11 月上旬红叶漫山，登高远眺西山层林尽染，是北京秋天的仪式感所在。',
    tips: [
      '红叶季周末人流巨大，尽量工作日或清晨早出发',
      '北门缆车可节省体力，适合带老人孩子',
      '山上补给点价格偏高，建议自带饮水',
    ],
  },
  {
    id: 'yuelushan',
    name: '岳麓山',
    subtitle: '城市里的千年名山',
    province: '湖南 · 长沙',
    region: '华中',
    elevation: 300,
    difficulty: 1,
    distance: 4,
    duration: '1-2 小时',
    scenery: 4.2,
    bestSeason: '11-12 月（枫叶）',
    tags: ['爱晚亭', '岳麓书院', '夜爬', '免费'],
    emoji: '📖',
    colors: ['#9ad0ec', '#e8f6fd', '#8bc34a', '#558b2f'],
    description: '岳麓山坐落长沙城中，山脚岳麓书院千年弦歌不绝，爱晚亭因“停车坐爱枫林晚”而得名。免费开放、交通便利，白天看枫、傍晚看日落、夜里数星星，是长沙人最日常的山。',
    tips: [
      '夜爬建议结伴并带头灯，主路有灯但支路较暗',
      '秋季爱晚亭一带枫叶正红，最佳观赏期在 12 月初',
      '山顶观景台可俯瞰橘子洲与湘江全景',
    ],
  },
  {
    id: 'baiyunshan',
    name: '白云山',
    subtitle: '广州绿肺 · 羊城第一秀',
    province: '广东 · 广州',
    region: '华南',
    elevation: 382,
    difficulty: 1,
    distance: 6,
    duration: '2-3 小时',
    scenery: 4.1,
    bestSeason: '10 月-次年 3 月',
    tags: ['城市公园', '亲子', '晨运'],
    emoji: '🌿',
    colors: ['#a5c8e8', '#eef7ff', '#6fae6f', '#3f7d4a'],
    description: '白云山是广州市区最大的自然山地公园，摩星岭为最高点。晨雾缭绕时如置身白云之间，故得此名。索道、步道与盘山公路四通八达，晨运、遛娃、看日落皆宜，老少咸宜。',
    tips: [
      '清晨登山凉快人少，是本地晨运黄金时段',
      '南门索道排队人少，可作备选',
      '摩星岭山顶广场是看日落的经典机位',
    ],
  },
  {
    id: 'qingchengshan',
    name: '青城山',
    subtitle: '青城天下幽 · 道教发源地',
    province: '四川 · 都江堰',
    region: '西南',
    elevation: 1260,
    difficulty: 2,
    distance: 8,
    duration: '3-4 小时',
    scenery: 4.5,
    bestSeason: '4-10 月',
    tags: ['道教名山', '避暑', '世界遗产'],
    emoji: '☯️',
    colors: ['#a8c8b8', '#e4f1e7', '#5f8d6e', '#39634a'],
    description: '青城山是道教发源地之一，“青城天下幽”名不虚传。前山宫观林立、香火鼎盛，后山飞泉幽谷、人少清净，与都江堰同列世界文化遗产。盛夏山间清凉，是成都人的避暑后花园。',
    tips: [
      '前山看文化、后山看风景，时间有限建议择一深度游',
      '月城湖坐船可省一段平路，带老人孩子推荐',
      '夏季多雨，出发前留意天气并备防滑鞋',
    ],
  },
  {
    id: 'lushan',
    name: '庐山',
    subtitle: '飞流直下三千尺',
    province: '江西 · 九江',
    region: '华东',
    elevation: 1474,
    difficulty: 3,
    distance: 20,
    duration: '2 天',
    scenery: 4.7,
    bestSeason: '5-9 月（避暑）',
    tags: ['瀑布', '云雾', '避暑', '云中山城'],
    emoji: '💧',
    colors: ['#9fb8c8', '#e6eef2', '#6a8f9e', '#43677a'],
    description: '庐山以云雾、瀑布与老别墅群闻名。三叠泉落差 155 米气势磅礴，含鄱口是观日出绝佳位置，牯岭镇则像一座云中山城。李白一句“飞流直下三千尺”，让庐山瀑布名传千年。',
    tips: [
      '三叠泉台阶往返较累，量力而行并留足时间',
      '山区常年多雾，备好防滑鞋和轻便雨衣',
      '观光车票按有效期售卖，按行程天数购买更划算',
    ],
  },
  {
    id: 'tianmenshan',
    name: '天门山',
    subtitle: '天门洞开 · 通天大道',
    province: '湖南 · 张家界',
    region: '华中',
    elevation: 1518,
    difficulty: 2,
    distance: 6,
    duration: '3-4 小时（含栈道）',
    scenery: 4.8,
    bestSeason: '4-6 月、9-10 月',
    tags: ['天门洞', '玻璃栈道', '索道', '999 级天梯'],
    emoji: '🚡',
    colors: ['#95a5d0', '#e0e4f5', '#7d6fb0', '#544a86'],
    description: '天门山索道全长 7455 米，堪称世界最长高山客运索道之一。999 级上天梯直通天门洞，玻璃栈道悬于千米绝壁，鬼谷栈道云雾缭绕，是张家界最震撼的城市山岳景观。',
    tips: [
      '玻璃栈道需现场购买鞋套（5 元）',
      '旺季索道排队久，建议赶早上第一批',
      '山顶气温明显低于市区，即使夏天也带件薄外套',
    ],
  },
  {
    id: 'siguniangshan',
    name: '四姑娘山大峰',
    subtitle: '5000 米级入门雪山',
    province: '四川 · 阿坝',
    region: '西南',
    elevation: 5025,
    difficulty: 5,
    distance: 16,
    duration: '3 天（含海拔适应）',
    scenery: 4.9,
    bestSeason: '5-6 月、9-10 月',
    tags: ['雪山', '冰川', '高原', '需向导'],
    emoji: '🏔️',
    colors: ['#bfe3f2', '#f4fbff', '#a8cfe0', '#7ea8c0'],
    description: '四姑娘山大峰是公认的 5000 米级入门雪山，技术要求低但海拔不低。从海子沟进山，沿途可远眺幺妹峰与冰川，凌晨冲顶看云海日出，是许多山友的人生清单第一座雪山。',
    tips: [
      '务必聘请持证向导，并预留 1-2 天适应海拔',
      '出现高反及时下撤，量力而行不逞强',
      '冰爪、头灯、羽绒、手套等装备缺一不可',
    ],
  },
  {
    id: 'hengshan_n',
    name: '恒山',
    subtitle: '北岳恒山 · 悬空奇观',
    province: '山西 · 大同',
    region: '华北',
    elevation: 2016,
    difficulty: 2,
    distance: 10,
    duration: '4-5 小时',
    scenery: 4.4,
    bestSeason: '5-10 月',
    tags: ['五岳', '悬空寺', '边塞'],
    emoji: '🕌',
    colors: ['#d9b382', '#f4e3c8', '#a8825a', '#6f5236'],
    description: '北岳恒山地处塞上，山势雄浑苍茫。山下悬空寺如浮雕嵌于翠屏峰崖壁，建成 1500 余年屹立不倒，李白醉题“壮观”二字。果老岭、姑嫂崖等景点串起道教文化与边塞风光。',
    tips: [
      '悬空寺登临需另购票且每日限流，建议提前预约',
      '大同早晚温差大，夏季也备一件外套',
      '可与云冈石窟串成一线，安排两天更从容',
    ],
  },
  {
    id: 'hengshan_s',
    name: '衡山',
    subtitle: '南岳独秀 · 香火千年',
    province: '湖南 · 衡阳',
    region: '华中',
    elevation: 1300,
    difficulty: 2,
    distance: 12,
    duration: '4-6 小时',
    scenery: 4.5,
    bestSeason: '5-10 月、12-2 月（雾凇）',
    tags: ['五岳', '祝融峰', '日出', '祈福'],
    emoji: '🕯️',
    colors: ['#98d8bb', '#e8f9f0', '#6db389', '#3f8563'],
    description: '南岳衡山以“秀”著称，祝融峰之高、藏经殿之秀、水帘洞之奇、方广寺之深并称“衡山四绝”。山上香火千年不绝，登顶祝融峰看日出云海，是湘中一带山友的经典周末。',
    tips: [
      '冬季雾凇季路面结冰，注意保暖与防滑',
      '夜爬看日出的人很多，结伴同行更安全',
      '山脚南岳大庙值得顺路一游',
    ],
  },
  {
    id: 'songshan',
    name: '嵩山',
    subtitle: '中岳嵩山 · 禅宗祖庭',
    province: '河南 · 登封',
    region: '华中',
    elevation: 1491,
    difficulty: 3,
    distance: 8,
    duration: '4-5 小时',
    scenery: 4.5,
    bestSeason: '4-6 月、9-11 月',
    tags: ['五岳', '少林寺', '三皇寨', '书卷崖'],
    emoji: '🥋',
    colors: ['#d8c8a8', '#f3ecda', '#b09b72', '#7a6a4a'],
    description: '中岳嵩山是儒释道三教荟萃之地，山脚少林寺名扬天下。三皇寨栈道悬于书卷崖之上，连天大峡谷奇峰林立；太室山峻极顶大气磅礴，嵩阳书院更添千年文脉。',
    tips: [
      '三皇寨吊桥段悬空较高，恐高者提前评估路线',
      '少林寺加塔林半天即可逛完，可与大环线组合',
      '少室山步道路面碎石多，穿抓地好的登山鞋',
    ],
  },
  {
    id: 'changbaishan',
    name: '长白山',
    subtitle: '关东第一山 · 天池圣境',
    province: '吉林 · 延边',
    region: '东北',
    elevation: 2691,
    difficulty: 3,
    distance: 8,
    duration: '1 天（北坡/西坡）',
    scenery: 4.9,
    bestSeason: '6-9 月（冬季滑雪温泉）',
    tags: ['天池', '火山', '温泉', '林海'],
    emoji: '🌋',
    colors: ['#9fc9e8', '#eaf5fc', '#7fa8c0', '#4f7590'],
    description: '长白山是中朝界山，山顶天池如碧玉镶嵌于火山口，十六峰环列。北坡瀑布温泉、西坡高山花园、谷底林海各具风韵，登主峰俯瞰天池是东北旅行的高光时刻。',
    tips: [
      '天池天气多变，能否一睹全貌全凭运气，多留半天余量',
      '西坡 1442 级台阶上去视野最开阔，北坡可乘车直达',
      '山顶风大温低，夏季也要备防风外套',
    ],
  },
  {
    id: 'qianshan',
    name: '千山',
    subtitle: '东北明珠 · 弥勒道场',
    province: '辽宁 · 鞍山',
    region: '东北',
    elevation: 708,
    difficulty: 1,
    distance: 6,
    duration: '3-4 小时',
    scenery: 4.3,
    bestSeason: '4-10 月',
    tags: ['寺庙', '奇峰', '亲子', '城市周边'],
    emoji: '🛕',
    colors: ['#b8d8b8', '#eef7ee', '#88aa8a', '#55775a'],
    description: '千山素有“东北明珠”之称，九百九十九座峰如莲花叠翠，五大禅林古刹散落其间。峰奇石怪、松古泉清，天然弥勒大佛更是奇观，是辽东最亲民的登山胜地。',
    tips: [
      '五佛顶是最高点，缆车可省一半体力',
      '大佛景区与中部核心区分开售票，按体力取舍',
      '春季梨花盛开时最上镜',
    ],
  },
  {
    id: 'wutaishan',
    name: '五台山',
    subtitle: '四大佛教名山之首 · 华北屋脊',
    province: '山西 · 忻州',
    region: '华北',
    elevation: 3061,
    difficulty: 3,
    distance: 50,
    duration: '2-3 天（大朝台）',
    scenery: 4.6,
    bestSeason: '5-9 月',
    tags: ['佛教名山', '朝台', '清凉山', '徒步'],
    emoji: '🙏',
    colors: ['#e8c98a', '#f9efd8', '#b0925e', '#7d6438'],
    description: '五台山由五座台顶环抱而成，文殊菩萨道场，北台叶斗峰海拔 3061 米为华北最高。徒步大朝台串联五台，经幡猎猎、云海佛光，是山友心中的朝圣经典线。',
    tips: [
      '大朝台全程约 50 公里，顺时针逆时针各有讲究，提前做功课',
      '台顶昼夜温差极大，盛夏夜温也可近 0 度',
      '台怀镇寺庙群集中，体力有限可只做小朝台',
    ],
  },
  {
    id: 'xiaowutaishan',
    name: '小五台山',
    subtitle: '河北屋脊 · 华北户外圣地',
    province: '河北 · 张家口',
    region: '华北',
    elevation: 2882,
    difficulty: 5,
    distance: 25,
    duration: '2 天（重装穿越）',
    scenery: 4.5,
    bestSeason: '6-9 月',
    tags: ['重装', '金莲花', '穿越', '华北之巅'],
    emoji: '⛰️',
    colors: ['#a8c8a0', '#edf5ea', '#7a9a72', '#4c6b45'],
    description: '小五台山五峰簇立，东台海拔 2882 米为河北之巅。这里是华北重装徒步的试金石，七月金莲花开满山脊，裸岩草甸云雾相接，风光与强度并称华北之最。',
    tips: [
      '属国家级自然保护区，进山需提前登记备案',
      '山脊无水源遮蔽，重装需带足水与防风装备',
      '天气多变，雷雨季务必规划撤退路线',
    ],
  },
  {
    id: 'lingshan',
    name: '东灵山',
    subtitle: '北京之巅 · 高山草甸',
    province: '北京 · 门头沟',
    region: '华北',
    elevation: 2303,
    difficulty: 2,
    distance: 10,
    duration: '4-6 小时',
    scenery: 4.2,
    bestSeason: '5-10 月',
    tags: ['高山草甸', '北京之巅', '露营', '观星'],
    emoji: '🌄',
    colors: ['#a5c8b8', '#ecf5ef', '#76998a', '#47695a'],
    description: '东灵山海拔 2303 米，是北京地区的最高峰。山顶草甸平缓开阔，春夏野花铺地，秋季金黄一片，从江水河村登顶往返轻松，是京郊看星星看云海的绝佳去处。',
    tips: [
      '江水河村上山线路最短，新手也友好',
      '山顶风大，露营需抗风帐篷并看天气预报',
      '秋冬季节防火期部分线路封闭，行前确认',
    ],
  },
  {
    id: 'kongtongshan',
    name: '崆峒山',
    subtitle: '道教第一山 · 丝路雄关',
    province: '甘肃 · 平凉',
    region: '西北',
    elevation: 2123,
    difficulty: 2,
    distance: 7,
    duration: '4-5 小时',
    scenery: 4.4,
    bestSeason: '5-10 月',
    tags: ['道教名山', '黄帝问道', '丝路', '古建筑'],
    emoji: '🏯',
    colors: ['#c8b88a', '#f5eedb', '#96855e', '#665a3a'],
    description: '崆峒山西接六盘、东望关中，相传黄帝问道于广成子于此，是道教发祥地之一。雷声峰险、皇城建群，丹崖之上道观层叠，“中华道教第一山”名不虚传。',
    tips: [
      '中台是核心，皇城至香山一线最见气势',
      '可从后山步行上山省索道钱，前山缆车省时',
      '与平凉周边石窟联游更值',
    ],
  },
  {
    id: 'maijishan',
    name: '麦积山',
    subtitle: '秦地林朱之冠 · 东方雕塑馆',
    province: '甘肃 · 天水',
    region: '西北',
    elevation: 1742,
    difficulty: 1,
    distance: 3,
    duration: '2-3 小时',
    scenery: 4.6,
    bestSeason: '4-10 月',
    tags: ['石窟', '世界遗产', '亲子', '丝路'],
    emoji: '🗿',
    colors: ['#c9a87c', '#f4ead6', '#97795a', '#685238'],
    description: '麦积山因形如农家麦垛得名，丝绸之路上的艺术明珠。凌空栈道盘旋于百米崖壁，七千余尊泥塑石刻历经北魏至明清，被誉为“东方雕塑陈列馆”，登临如入空中佛国。',
    tips: [
      '栈道陡窄恐高者量力，参观需按线路单向通行',
      '清晨光线柔和，最适合观窟拍照',
      '可与仙人崖、净土寺串成一日',
    ],
  },
  {
    id: 'helanshan',
    name: '贺兰山',
    subtitle: '塞上屏障 · 岩画长廊',
    province: '宁夏 · 银川',
    region: '西北',
    elevation: 3556,
    difficulty: 4,
    distance: 12,
    duration: '1-2 天',
    scenery: 4.3,
    bestSeason: '5-9 月',
    tags: ['岩画', '边塞', '徒步', '西北风光'],
    emoji: '🐎',
    colors: ['#d8b898', '#f5ece0', '#a08668', '#6e5840'],
    description: '贺兰山雄峙宁夏平原之西，挡住腾格里风沙，造就“塞上江南”。山口岩画绵延千米记录游牧千年，登主峰敖包疙瘩俯瞰大漠与黄河相望，苍凉雄浑是西北独有的气质。',
    tips: [
      '岩画区平缓适合大众，登主峰需向导与充足补给',
      '昼夜温差极大，防晒与保暖并重',
      '苏峪口、贺兰口是主要进山口，缆车可上青松岭',
    ],
  },
  {
    id: 'wudangshan',
    name: '武当山',
    subtitle: '道教第一名山 · 太极祖庭',
    province: '湖北 · 十堰',
    region: '华中',
    elevation: 1612,
    difficulty: 2,
    distance: 9,
    duration: '1-2 天',
    scenery: 4.7,
    bestSeason: '4-6 月、9-11 月',
    tags: ['道教名山', '太极', '世界遗产', '金顶'],
    emoji: '☯️',
    colors: ['#98b8c8', '#e8f2f7', '#6f8fa0', '#42606f'],
    description: '武当山北通秦岭、南接巴山，明成祖“北建故宫、南修武当”成就九宫八观。金顶铜殿鎏金映日，紫霄宫深藏幽谷，张三丰于此创太极，仙山琼阁不负“亘古无双胜境”。',
    tips: [
      '金顶另收门票，日出时云海佛光最美',
      '徒步明神道上金顶约 3 小时，古道石阶保存完好',
      '太子坡至逍遥谷一线清幽，适合慢游',
    ],
  },
  {
    id: 'shennongjia',
    name: '神农架',
    subtitle: '华中屋脊 · 物种基因库',
    province: '湖北 · 神农架林区',
    region: '华中',
    elevation: 3105,
    difficulty: 4,
    distance: 30,
    duration: '2-3 天（穿越）',
    scenery: 4.6,
    bestSeason: '5-10 月',
    tags: ['原始森林', '金丝猴', '避暑', '神农顶'],
    emoji: '🌲',
    colors: ['#8fb89a', '#eaf4ec', '#67967a', '#3d6b52'],
    description: '神农架以神农氏搭架采药得名，华中屋脊之上原始洪荒。神农顶云海翻涌，大九湖湿地如镜，金丝猴穿行林间，传说中野人出没之地，是华中最后的秘境。',
    tips: [
      '景区间距离远，自驾或包车最方便',
      '大九湖晨雾在日出后半小时最美，务必早起',
      '核心保护区禁止擅入，按开放线路游览',
    ],
  },
  {
    id: 'laojunshan',
    name: '老君山',
    subtitle: '伏牛之巅 · 云上金顶',
    province: '河南 · 洛阳',
    region: '华中',
    elevation: 2217,
    difficulty: 2,
    distance: 6,
    duration: '3-5 小时',
    scenery: 4.7,
    bestSeason: '4-6 月、9-11 月、冬季雪景',
    tags: ['道教名山', '金顶', '云海', '雪景'],
    emoji: '⛩️',
    colors: ['#b0a0c8', '#efecf7', '#8578a0', '#564c73'],
    description: '老君山为伏牛山主峰，相传老子归隐修炼于此。十里画屏石峰如林，金顶道观群凌驾云端，雪后“远赴人间惊鸿宴”的雪景火爆全网，是近年最出片的中原名山。',
    tips: [
      '两段索道接力上金顶，徒步爱好者可走十里画屏',
      '雪季金顶银装素裹最震撼，注意防滑保暖',
      '夜爬看日出是年轻人的新玩法，结伴而行',
    ],
  },
  {
    id: 'yuntaishan',
    name: '云台山',
    subtitle: '红石奇峡 · 北方水世界',
    province: '河南 · 焦作',
    region: '华中',
    elevation: 1308,
    difficulty: 1,
    distance: 8,
    duration: '1 天',
    scenery: 4.6,
    bestSeason: '5-9 月（丰水期）',
    tags: ['峡谷', '瀑布', '红石', '世界地质公园'],
    emoji: '💦',
    colors: ['#c89090', '#f7eaea', '#a06a62', '#6e413c'],
    description: '云台山以红石峡丹崖碧水闻名，红岩绝壁间飞瀑清潭相连，314 米的云台天瀑落差惊人。茱萸峰上王维“遥知兄弟登高处”的千古吟咏，让这里既有水灵又有文气。',
    tips: [
      '红石峡单向通行，早上人少体验最佳',
      '丰水期瀑布才壮观，出行前看近期降雨',
      '园区大，景区巴士接驳高效，按线路规划顺序',
    ],
  },
  {
    id: 'jigongshan',
    name: '鸡公山',
    subtitle: '中国四大避暑胜地之一',
    province: '河南 · 信阳',
    region: '华中',
    elevation: 768,
    difficulty: 1,
    distance: 5,
    duration: '2-4 小时',
    scenery: 4.1,
    bestSeason: '6-9 月避暑',
    tags: ['避暑', '老别墅', '民国风情', '亲子'],
    emoji: '🏘️',
    colors: ['#a8c0a0', '#eef5ea', '#7c9674', '#4e6b47'],
    description: '鸡公山雄踞豫楚之间，报晓峰形似雄鸡引颈啼鸣。清末民初各国老别墅散落山间，与庐山、莫干山、北戴河并称四大避暑胜地，盛夏清凉，云海日出皆是寻常。',
    tips: [
      '颐庐与老别墅群是精华，徒步串游约半天',
      '夏季均温 24 度，避暑首选',
      '波尔登森林公园相邻，可顺游',
    ],
  },
  {
    id: 'yandangshan',
    name: '雁荡山',
    subtitle: '海上名山 · 褒中绝胜',
    province: '浙江 · 温州',
    region: '华东',
    elevation: 1056,
    difficulty: 2,
    distance: 8,
    duration: '1-2 天',
    scenery: 4.6,
    bestSeason: '4-6 月、9-11 月',
    tags: ['奇峰', '夜景', '瀑布', '世界地质公园'],
    emoji: '🗻',
    colors: ['#98a8c0', '#ecf0f7', '#6f7f98', '#42526a'],
    description: '雁荡山因山顶雁湖芦苇丛生、秋雁宿之得名，流纹岩地貌造就灵峰奇、灵岩秀、大龙湫飞瀑奇的“雁荡三绝”。日观奇峰夜赏剪影，移步换形堪称东南第一山。',
    tips: [
      '灵峰夜景必须看，剪刀峰日夜形态迥异',
      '大龙湫水量雨后最大，行前留意天气',
      '方洞栈道悬于绝壁，恐高者慎入',
    ],
  },
  {
    id: 'tianmushan',
    name: '天目山',
    subtitle: '大树王国 · 东南佛教名山',
    province: '浙江 · 杭州',
    region: '华东',
    elevation: 1506,
    difficulty: 2,
    distance: 6,
    duration: '3-4 小时',
    scenery: 4.4,
    bestSeason: '4-10 月',
    tags: ['古树', '避暑', '森林', '禅宗'],
    emoji: '🌳',
    colors: ['#9cb890', '#eef5ea', '#71946a', '#456640'],
    description: '天目山东西两峰峰顶各有一池如目而得名，古木参天号称“大树王国”，万年银杏与五代同堂的古柳杉令人惊叹。禅源寺钟声悠远，盛夏均温仅 25 度，是江南清凉秘境。',
    tips: [
      '开山老殿至大树王一线是精华徒步线',
      '原始森林区步道湿滑，穿防滑鞋',
      '夏季避暑一房难求，需提前订住',
    ],
  },
  {
    id: 'moganshan',
    name: '莫干山',
    subtitle: '江南第一山 · 民宿之都',
    province: '浙江 · 湖州',
    region: '华东',
    elevation: 724,
    difficulty: 1,
    distance: 5,
    duration: '2-3 小时',
    scenery: 4.3,
    bestSeason: '4-11 月',
    tags: ['避暑', '竹海', '民宿', '亲子'],
    emoji: '🎋',
    colors: ['#a0c898', '#eef7ec', '#74a06c', '#43703f'],
    description: '莫干山因干将莫邪铸剑传说得名，竹海连山、泉瀑飞漱，与庐山北戴河并列避暑胜地。如今满山精品民宿已成度假地标，剑池飞瀑与民国别墅藏着旧时光。',
    tips: [
      '剑池瀑布与竹海步道半日可游完',
      '周未民宿爆满，务必提前预订',
      '自驾盘山路窄弯多，新手慢行',
    ],
  },
  {
    id: 'laoshan',
    name: '崂山',
    subtitle: '海上第一名山',
    province: '山东 · 青岛',
    region: '华东',
    elevation: 1132,
    difficulty: 2,
    distance: 7,
    duration: '4-6 小时',
    scenery: 4.6,
    bestSeason: '4-10 月',
    tags: ['道教名山', '海岸', '崂山矿泉', '观海'],
    emoji: '🌊',
    colors: ['#88b8d0', '#e8f5fb', '#5f8fa8', '#356078'],
    description: '崂山拔海而立，山海相连，素有“海上名山第一”之誉。巨峰观云海、太清宫访道教全真祖庭、仰口看海天一色，崂山矿泉水泡茶更是一绝，是山与海的双向奔赴。',
    tips: [
      '巨峰、太清、仰口、北九水各成体系，选一深度游',
      '北九水以水见长，丰水期最美',
      '夏季防晒必备，海边紫外线强',
    ],
  },
  {
    id: 'sanqingshan',
    name: '三清山',
    subtitle: '西太平洋边缘最美花岗岩',
    province: '江西 · 上饶',
    region: '华东',
    elevation: 1819,
    difficulty: 3,
    distance: 10,
    duration: '1-2 天',
    scenery: 4.8,
    bestSeason: '4-6 月、9-11 月',
    tags: ['花岗岩', '道教名山', '栈道', '云海'],
    emoji: '🗿',
    colors: ['#b0a8c8', '#f0edf7', '#827aa0', '#514a73'],
    description: '三清山因玉京玉虚玉华三峰如道教三清列坐得名。巨蟒出山、东方女神等花岗岩奇观举世罕见，高空栈道凌空蜿蜒，云雾升腾时恍若仙境，被誉为世界最美的花岗岩廊道。',
    tips: [
      '高空栈道全程约 4 公里，恐高者提前心理建设',
      '日出东方女神侧影最佳机位在玉台',
      '索道旺季排队久，赶早入园',
    ],
  },
  {
    id: 'jinggangshan',
    name: '井冈山',
    subtitle: '革命摇篮 · 雄踞罗霄',
    province: '江西 · 吉安',
    region: '华东',
    elevation: 1597,
    difficulty: 2,
    distance: 9,
    duration: '1-2 天',
    scenery: 4.3,
    bestSeason: '4-10 月',
    tags: ['红色圣地', '杜鹃', '云海', '竹海'],
    emoji: '🌾',
    colors: ['#c8a890', '#f5ede6', '#9a7a62', '#6b4f3c'],
    description: '井冈山地处罗霄山脉中段，群峰竞秀、飞瀑成群，黄洋界云海雄浑，十里杜鹃长廊春日如霞。作为中国革命摇篮，红色史迹与绿色山水在此交相辉映。',
    tips: [
      '黄洋界看云海日出，清晨最佳',
      '四五月杜鹃花海沿十里长廊铺开',
      '核心景区观光车通票制，规划好线路顺序',
    ],
  },
  {
    id: 'longhushan',
    name: '龙虎山',
    subtitle: '道教祖庭 · 丹霞碧水',
    province: '江西 · 鹰潭',
    region: '华东',
    elevation: 1300,
    difficulty: 1,
    distance: 6,
    duration: '1 天',
    scenery: 4.5,
    bestSeason: '4-10 月',
    tags: ['道教名山', '丹霞', '悬棺', '竹筏'],
    emoji: '🐉',
    colors: ['#c89a78', '#f5eadb', '#9a704f', '#6b4830'],
    description: '龙虎山是道教正一派祖庭，张天师世居于此。泸溪河畔丹霞碧水如画廊展开，乘竹筏看仙水岩崖墓悬棺千年之谜，升棺表演与天师府道韵相映成趣，山水人文皆绝。',
    tips: [
      '竹筏漂流是精华，全程约 1 小时慢游',
      '悬棺升棺表演每日数场，留意时刻表',
      '夏季河边暴晒，防晒帽必备',
    ],
  },
  {
    id: 'danxiashan',
    name: '丹霞山',
    subtitle: '丹霞地貌命名地',
    province: '广东 · 韶关',
    region: '华南',
    elevation: 619,
    difficulty: 1,
    distance: 7,
    duration: '1 天',
    scenery: 4.5,
    bestSeason: '4-6 月、9-11 月',
    tags: ['丹霞', '世界遗产', '日出', '情侣峰'],
    emoji: '🪨',
    colors: ['#d08860', '#f7e4d6', '#a05c3a', '#6e3820'],
    description: '丹霞山是全球丹霞地貌的命名地，赤壁丹崖如霞光万丈。阳元石、阴元石天工奇观令人惊叹，锦江碧水绕山而行，晨雾中泛舟江上，山色如染，是世界自然遗产。',
    tips: [
      '长老峰看日出是经典，凌晨需打灯登山',
      '翔龙湖与锦江游船可省不少脚程',
      '夏季炎热，清晨傍晚出游最舒适',
    ],
  },
  {
    id: 'maoershan',
    name: '猫儿山',
    subtitle: '华南之巅 · 漓江源头',
    province: '广西 · 桂林',
    region: '华南',
    elevation: 2141,
    difficulty: 3,
    distance: 10,
    duration: '4-6 小时',
    scenery: 4.5,
    bestSeason: '4-10 月',
    tags: ['华南之巅', '云海', '杜鹃', '露营'],
    emoji: '🐱',
    colors: ['#98c8b0', '#ecf7f1', '#6fa088', '#3f7059'],
    description: '猫儿山海拔 2141 米，为华南第一高峰，漓江、资江、浔江皆发源于此。山巅老界杜鹃林带春日如燃，云海佛光频现，秋看星空冬赏雾凇，是华南山友心中的圣山。',
    tips: [
      '自驾至山门后徒步登顶，夜爬看日出需结伴',
      '山顶气温比桂林市区低 10 度以上，备外套',
      '五六月杜鹃花期为最美季节',
    ],
  },
  {
    id: 'wuzhishan',
    name: '五指山',
    subtitle: '海南之巅 · 雨林秘境',
    province: '海南 · 五指山市',
    region: '华南',
    elevation: 1867,
    difficulty: 4,
    distance: 12,
    duration: '1 天（登顶）',
    scenery: 4.4,
    bestSeason: '11-4 月（旱季）',
    tags: ['热带雨林', '海南之巅', '昌化江源', '黎乡'],
    emoji: '🌴',
    colors: ['#78c0a0', '#e8f7ef', '#4f967a', '#2c6b52'],
    description: '五指山五峰如指撑天，是海南岛的脊梁与昌化江源头。热带原始雨林藤蔓缠绕、板根如墙，登顶之路野趣十足，山巅可望云海漫过千峰，黎苗风情环绕山下。',
    tips: [
      '登顶线路原始需当地向导，雨季蚂蟥多',
      '旱季 11 月至次年 4 月最宜，台风季勿往',
      '昌化江源头栈道平缓，是雨林入门好选择',
    ],
  },
  {
    id: 'putuoshan',
    name: '普陀山',
    subtitle: '海天佛国 · 观音道场',
    province: '浙江 · 舟山',
    region: '华东',
    elevation: 291,
    difficulty: 1,
    distance: 5,
    duration: '1-2 天',
    scenery: 4.6,
    bestSeason: '4-6 月、9-11 月',
    tags: ['佛教名山', '海岛', '观音', '海蚀地貌'],
    emoji: '🙏',
    colors: ['#88b8c8', '#eaf5f8', '#5f8fa0', '#35606f'],
    description: '普陀山孤悬东海莲花洋中，观音菩萨道场，“海天佛国”四字道尽其妙。短姑道头、千步金沙、佛顶山慧济禅寺，山海与梵音相和，是四大佛教名山中最玲珑的一座。',
    tips: [
      '朱家尖蜈蚣峙码头上岛，旺季船票要抢',
      '佛顶山可乘索道，步行香云路千级石阶更虔诚',
      '岛上物价高，可适量自带饮水干粮',
    ],
  },
  {
    id: 'fanjingshan',
    name: '梵净山',
    subtitle: '梵天净土 · 天空之城',
    province: '贵州 · 铜仁',
    region: '西南',
    elevation: 2572,
    difficulty: 3,
    distance: 7,
    duration: '1 天',
    scenery: 4.8,
    bestSeason: '4-6 月、9-11 月',
    tags: ['世界遗产', '弥勒道场', '金顶', '珙桐'],
    emoji: '🛕',
    colors: ['#98a8c8', '#ecf0f7', '#6f7f9a', '#42506b'],
    description: '梵净山是武陵山脉主峰，弥勒菩萨道场，世界自然遗产。红云金顶孤峰擎天，一桥飞架两庙，云瀑禅雾变幻莫测，黔金丝猴与珙桐花藏于原始林间，被誉为“天空之城”。',
    tips: [
      '每日限流，门票索道务必提前网上预订',
      '登金顶石阶陡峭需手脚并用，恐高慎行',
      '山顶天气瞬变，雨衣比雨伞实用',
    ],
  },
  {
    id: 'jinfoshan',
    name: '金佛山',
    subtitle: '南方喀斯特秘境',
    province: '重庆 · 南川',
    region: '西南',
    elevation: 2251,
    difficulty: 2,
    distance: 8,
    duration: '1 天',
    scenery: 4.4,
    bestSeason: '4-10 月（冬季赏雪）',
    tags: ['喀斯特', '世界遗产', '杜鹃', '滑雪'],
    emoji: '🏔️',
    colors: ['#a0b8c8', '#eef4f7', '#75909f', '#476270'],
    description: '金佛山为重庆名山之首，喀斯特桌山地貌世界罕见，世界自然遗产。古佛洞深邃神秘，高山杜鹃春日漫山，冬季山顶积雪可滑雪，是重庆人的避暑赏雪后花园。',
    tips: [
      '索道直达山顶，古佛洞恒温 11 度记得加衣',
      '四月杜鹃花海沿绝壁绽放最壮观',
      '冬季雪期短，想滑雪需盯紧天气预报',
    ],
  },
  {
    id: 'cangshan',
    name: '苍山',
    subtitle: '大理风花雪月之雪',
    province: '云南 · 大理',
    region: '西南',
    elevation: 4122,
    difficulty: 3,
    distance: 18,
    duration: '1 天（玉带路）',
    scenery: 4.7,
    bestSeason: '3-6 月、9-11 月',
    tags: ['洱海', '玉带云游路', '杜鹃', '雪山'],
    emoji: '🏔️',
    colors: ['#98c0d0', '#ebf6fa', '#6f98a8', '#3f6a7a'],
    description: '苍山十九峰横亘大理坝子之西，马龙峰积雪经夏不化，与洱海月共成风花雪月之景。玉带云游路悬于半山，一路俯瞰洱海田园，洗马潭高山杜鹃春末如焰。',
    tips: [
      '感通索道+玉带路一线最经典，俯瞰洱海绝佳',
      '高海拔紫外线强，防晒不可少',
      '洗马潭大索道直达 3900 米，恐高晕高者注意',
    ],
  },
  {
    id: 'jizushan',
    name: '鸡足山',
    subtitle: '迦叶道场 · 佛教灵山',
    province: '云南 · 大理',
    region: '西南',
    elevation: 3248,
    difficulty: 3,
    distance: 12,
    duration: '1-2 天',
    scenery: 4.5,
    bestSeason: '3-6 月、9-11 月',
    tags: ['佛教名山', '日出', '祝圣寺', '朝圣'],
    emoji: '🙏',
    colors: ['#c0b090', '#f5f0e0', '#908060', '#635436'],
    description: '鸡足山前伸三趾后舒一足，形似鸡足而得名，迦叶尊者守衣入定之地。天柱峰金顶寺东观日出、西看苍山洱海、南睹祥云、北望玉龙，四观风光冠绝滇西。',
    tips: [
      '祝圣寺为进山第一站，古刹清幽值得细逛',
      '索道到索道下站后仍需爬升，留足体力',
      '与大理古城串联，两天行程最从容',
    ],
  },
  {
    id: 'habaxueshan',
    name: '哈巴雪山',
    subtitle: '人生第一座雪山首选',
    province: '云南 · 香格里拉',
    region: '西南',
    elevation: 5396,
    difficulty: 5,
    distance: 14,
    duration: '2-3 天（含适应）',
    scenery: 4.7,
    bestSeason: '5-6 月、9-10 月',
    tags: ['雪山', '入门攀登', '雪线', '需向导'],
    emoji: '❄️',
    colors: ['#a8d0e0', '#f0f9fc', '#7fa8b8', '#4f7888'],
    description: '哈巴雪山与玉龙雪山隔虎跳峡相望，攀登难度温和、成功率高，是公认的“人生第一座雪山”。登顶日踏雪坡过碎石，日出时分梅里般的金光洒在峰顶，此生难忘。',
    tips: [
      '需注册向导队，冰雪季技术装备必备',
      '大本营 4100 米，提前一天抵达适应海拔',
      '高反症状明显时果断下撤，山永远都在',
    ],
  },
  {
    id: 'gonggashan',
    name: '贡嘎山',
    subtitle: '蜀山之王 · 雪山之巅',
    province: '四川 · 康定',
    region: '西南',
    elevation: 7556,
    difficulty: 5,
    distance: 45,
    duration: '6-8 天（徒步）',
    scenery: 5.0,
    bestSeason: '5-6 月、9-10 月',
    tags: ['极高山', '蜀山之王', '徒步圣地', '日照金山'],
    emoji: '🏔️',
    colors: ['#a8c0d8', '#f0f6fc', '#7f98b0', '#4f687f'],
    description: '贡嘎山海拔 7556 米，为四川省最高峰，尊为“蜀山之王”。其垂直落差冠绝群山，子梅垭口与冷嘎措的日照金山是摄影师此生必看画面，贡嘎大环线更是中国顶级徒步线。',
    tips: [
      '主峰为技术型攀登仅限专业队伍，普通山友以徒步观山为主',
      '冷嘎措拍倒影日照金山，下午到达等日落',
      '徒步线海拔多在 4000 米以上，防高反装备齐全',
    ],
  },
];

const REGIONS = ['全部', '华东', '华北', '华中', '华南', '西南', '西北'];
const DIFFS = [
  { key: '全部', label: '全部', min: 1, max: 5 },
  { key: '休闲', label: '休闲 🚶', min: 1, max: 2 },
  { key: '进阶', label: '进阶 🎒', min: 3, max: 3 },
  { key: '挑战', label: '挑战 💪', min: 4, max: 5 },
];
const DIFF_LABELS = { 1: '休闲', 2: '轻松', 3: '进阶', 4: '困难', 5: '挑战' };
const WUYUE_IDS = ['taishan', 'huashan', 'hengshan_s', 'hengshan_n', 'songshan'];

/* 山峰坐标 [纬度, 经度]（山顶/主峰附近，用于距离计算） */
const COORDS = {
  taishan: [36.257, 117.101],
  huashan: [34.475, 110.085],
  huangshan: [30.131, 118.160],
  emeishan: [29.523, 103.332],
  wugongshan: [27.465, 114.175],
  xiangshan: [39.992, 116.190],
  yuelushan: [28.185, 112.937],
  baiyunshan: [23.182, 113.297],
  qingchengshan: [30.898, 103.563],
  lushan: [29.565, 115.976],
  tianmenshan: [29.052, 110.498],
  siguniangshan: [31.102, 102.897],
  hengshan_n: [39.674, 113.736],
  hengshan_s: [27.256, 112.683],
  songshan: [34.490, 113.040],
  changbaishan: [42.007, 128.057],
  qianshan: [41.055, 123.133],
  wutaishan: [39.117, 113.527],
  xiaowutaishan: [39.950, 115.033],
  lingshan: [40.058, 115.468],
  kongtongshan: [35.550, 106.616],
  maijishan: [34.356, 106.004],
  helanshan: [38.720, 105.950],
  wudangshan: [32.400, 111.000],
  shennongjia: [31.570, 110.330],
  laojunshan: [33.750, 111.650],
  yuntaishan: [35.430, 113.430],
  jigongshan: [31.820, 114.070],
  yandangshan: [28.370, 121.060],
  tianmushan: [30.340, 119.430],
  moganshan: [30.600, 119.860],
  laoshan: [36.160, 120.620],
  sanqingshan: [28.900, 118.050],
  jinggangshan: [26.560, 114.150],
  longhushan: [28.080, 116.990],
  danxiashan: [25.030, 113.740],
  maoershan: [25.880, 110.410],
  wuzhishan: [18.870, 109.660],
  putuoshan: [29.975, 122.383],
  fanjingshan: [27.920, 108.700],
  jinfoshan: [29.030, 107.180],
  cangshan: [25.680, 100.100],
  jizushan: [25.980, 100.380],
  habaxueshan: [27.320, 100.120],
  gonggashan: [29.600, 101.880],
};

/* 步步登峰 · 虚拟挑战山峰（日常爬升沿真实山径剖面前进） */
const CHALLENGES = [
  {
    id: 'taishan', name: '泰山', emoji: '🌄', elevation: 1545, suggest: '约 2 周',
    desc: '把每天的楼梯变成六千级台阶，从红门一路走到玉皇顶。',
    colors: ['#ff9d6e', '#ffe0b0', '#b06a3b', '#7a4629'],
    waypoints: [
      { alt: 250, name: '红门' }, { alt: 847, name: '中天门' }, { alt: 950, name: '云步桥' },
      { alt: 1300, name: '十八盘' }, { alt: 1460, name: '南天门' }, { alt: 1545, name: '玉皇顶' },
    ],
  },
  {
    id: 'huangshan', name: '黄山', emoji: '🌊', elevation: 1864, suggest: '约 3 周',
    desc: '一步一景，向莲花峰顶的云海进发。',
    colors: ['#8fc3dd', '#eaf6fa', '#7fa8b8', '#4f7583'],
    waypoints: [
      { alt: 370, name: '慈光阁' }, { alt: 700, name: '立马桥' }, { alt: 900, name: '半山寺' },
      { alt: 1660, name: '玉屏楼' }, { alt: 1864, name: '莲花峰' },
    ],
  },
  {
    id: 'huashan', name: '华山', emoji: '🧗', elevation: 2154, suggest: '约 4 周',
    desc: '自古华山一条路，垂直的台阶考验每天的你。',
    colors: ['#8e7cc3', '#d8cff0', '#8a86a8', '#565b73'],
    waypoints: [
      { alt: 400, name: '玉泉院' }, { alt: 1200, name: '青柯坪' }, { alt: 1600, name: '千尺幢' },
      { alt: 1614, name: '北峰' }, { alt: 1700, name: '苍龙岭' }, { alt: 2154, name: '南峰' },
    ],
  },
  {
    id: 'emeishan', name: '峨眉山', emoji: '🐘', elevation: 3079, suggest: '约 6 周',
    desc: '全程五十公里的朝圣路，用日常爬升丈量它。',
    colors: ['#f2d488', '#fdf3d0', '#7ba05b', '#4c6f3f'],
    waypoints: [
      { alt: 530, name: '报国寺' }, { alt: 780, name: '清音阁' }, { alt: 1120, name: '洪椿坪' },
      { alt: 1750, name: '仙峰寺' }, { alt: 2430, name: '雷洞坪' }, { alt: 3079, name: '金顶' },
    ],
  },
  {
    id: 'yulong', name: '玉龙雪山', emoji: '❄️', elevation: 5596, suggest: '约 3 个月',
    desc: '从甘海子到扇子陡，一日四季的雪线远征。',
    colors: ['#a8c8dd', '#eef7fb', '#9fc4d8', '#6f97b5'],
    waypoints: [
      { alt: 3100, name: '甘海子' }, { alt: 4506, name: '冰川公园' },
      { alt: 4680, name: '4680 观景台' }, { alt: 5596, name: '扇子陡' },
    ],
  },
  {
    id: 'everest', name: '珠穆朗玛峰', emoji: '🏔️', elevation: 8848, suggest: '约半年',
    desc: '用半年的日常爬升，走完人类最伟大的 8848 米。',
    colors: ['#b8d4e8', '#f0f8ff', '#c8dce8', '#8fb3cc'],
    waypoints: [
      { alt: 5364, name: '大本营' }, { alt: 6065, name: 'C1 营地' }, { alt: 6400, name: 'C2 营地' },
      { alt: 7162, name: 'C3 营地' }, { alt: 7925, name: '南坳' },
      { alt: 8790, name: '希拉里台阶' }, { alt: 8848, name: '顶峰' },
    ],
  },
];
