/* 爬山趣 · 山峰数据 */
'use strict';

const MOUNTAINS = [
  {
    id: 'taishan',
    name: '泰山',
    subtitle: '五岳之首 · 帝王封禅之地',
    province: '山东 · 泰安',
    region: '华东',
    elevation: 1545,
    difficulty: 3,
    distance: 9.5,
    duration: '4-6 小时',
    scenery: 4.9,
    bestSeason: '4-6 月、9-11 月',
    tags: ['五岳', '看日出', '文化名山', '夜爬'],
    emoji: '🌄',
    colors: ['#ff9d6e', '#ffe0b0', '#b06a3b', '#7a4629'],
    description: '泰山为五岳之首，素有“天下第一山”之称。从红门出发的经典中路徒步线全程约 9.5 公里，六千余级石阶串联斗母宫、中天门、十八盘，直至南天门与玉皇顶。夜爬泰山等待日出，是无数登山爱好者的启蒙之旅。',
    tips: [
      '山顶温差大，即使夏季也建议带一件外套',
      '夜爬约 22 点从红门出发，日出前抵达日观峰刚刚好',
      '十八盘台阶陡峭，走“之”字形可明显节省体力',
    ],
  },
  {
    id: 'huashan',
    name: '华山',
    subtitle: '奇险天下第一山',
    province: '陕西 · 渭南',
    region: '西北',
    elevation: 2154,
    difficulty: 5,
    distance: 12,
    duration: '6-8 小时（全程徒步）',
    scenery: 4.9,
    bestSeason: '4-6 月、9-10 月',
    tags: ['五岳', '长空栈道', '花岗岩', '险峰'],
    emoji: '🧗',
    colors: ['#8e7cc3', '#d8cff0', '#8a86a8', '#565b73'],
    description: '自古华山一条路。千尺幢、百尺峡、老君犁沟等险段相连，长空栈道悬于垂直崖壁之上，鹞子翻身挑战每一位登山者的胆量。建议西峰索道上、北峰索道下，一日遍览东西南北中五峰。',
    tips: [
      '长空栈道需另购安全绳票，旺季排队较久',
      '雨雾天气部分险段可能临时关闭，出发前查公告',
      '全程攀爬铁索，务必带一副手套',
    ],
  },
  {
    id: 'huangshan',
    name: '黄山',
    subtitle: '五岳归来不看山，黄山归来不看岳',
    province: '安徽 · 黄山市',
    region: '华东',
    elevation: 1864,
    difficulty: 4,
    distance: 14,
    duration: '7-9 小时（两日更佳）',
    scenery: 5.0,
    bestSeason: '3-5 月、9-11 月',
    tags: ['奇松', '云海', '日出', '温泉'],
    emoji: '🌊',
    colors: ['#8fc3dd', '#eaf6fa', '#7fa8b8', '#4f7583'],
    description: '黄山集奇松、怪石、云海、温泉、冬雪五绝于一身。前山雄伟、后山秀丽，迎客松、光明顶、始信峰与西海大峡谷是精华所在。雨后初晴的清晨，站在光明顶看云海翻涌，是黄山给登山者的最高礼遇。',
    tips: [
      '西海大峡谷冬季部分封闭，行前确认开放情况',
      '山顶住宿紧张，看日出需提前预订',
      '云海多出现在雨雪后放晴的清晨，可关注天气预报碰运气',
    ],
  },
  {
    id: 'emeishan',
    name: '峨眉山',
    subtitle: '四大佛教名山之一 · 普贤道场',
    province: '四川 · 乐山',
    region: '西南',
    elevation: 3079,
    difficulty: 4,
    distance: 50,
    duration: '2 天（全程徒步）',
    scenery: 4.8,
    bestSeason: '4-10 月',
    tags: ['佛教名山', '金顶', '猴群', '朝圣'],
    emoji: '🐘',
    colors: ['#f2d488', '#fdf3d0', '#7ba05b', '#4c6f3f'],
    description: '峨眉山是普贤菩萨道场，从报国寺徒步至金顶约需两日，沿途古寺林立、林深雾绕。金顶十方普贤像庄严宏伟，日出、云海、佛光、圣灯并称峨眉四大奇观。',
    tips: [
      '生态猴区注意收好食物和塑料袋，避免被猴群抢夺',
      '山脚到金顶海拔落差近 2600 米，防寒防雨都要准备',
      '体力有限可乘景区大巴至雷洞坪，再步行上金顶',
    ],
  },
  {
    id: 'wugongshan',
    name: '武功山',
    subtitle: '云中草原 · 十万亩高山草甸',
    province: '江西 · 萍乡',
    region: '华东',
    elevation: 1918,
    difficulty: 3,
    distance: 25,
    duration: '2 天（穿越线）',
    scenery: 4.7,
    bestSeason: '5-6 月、9-10 月',
    tags: ['高山草甸', '露营', '星空', '穿越'],
    emoji: '⛺',
    colors: ['#79b4b2', '#dff2ea', '#74b56f', '#4d8b57'],
    description: '武功山以十万亩高山草甸闻名，春夏绿浪翻滚，秋季金黄一片。经典穿越线从沈子村到明月山，绝望坡与发云界是全程精华，山顶星空与日出云海令人难忘，帐篷节已成徒步圈盛事。',
    tips: [
      '山顶风大且无遮挡，帐篷务必选抗风款并打好地钉',
      '穿越线补给点少，需按计划背足水和食物',
      '9-10 月草甸金黄，是一年中最美的季节',
    ],
  },
  {
    id: 'xiangshan',
    name: '香山',
    subtitle: '北京最亲民的赏秋地',
    province: '北京 · 海淀',
    region: '华北',
    elevation: 575,
    difficulty: 1,
    distance: 5,
    duration: '2-3 小时',
    scenery: 4.3,
    bestSeason: '10 月中旬-11 月上旬',
    tags: ['红叶', '亲子', '城市周边'],
    emoji: '🍁',
    colors: ['#f2a65a', '#fbd9b0', '#d1603d', '#96351d'],
    description: '香山公园距北京城区不远，香炉峰海拔虽只有 575 米，视野却极佳。每年 10 月中旬至 11 月上旬红叶漫山，登高远眺西山层林尽染，是北京秋天的仪式感所在。',
    tips: [
      '红叶季周末人流巨大，尽量工作日或清晨早出发',
      '北门缆车可节省体力，适合带老人孩子',
      '山上补给点价格偏高，建议自带饮水',
    ],
  },
  {
    id: 'yuelushan',
    name: '岳麓山',
    subtitle: '城市里的千年名山',
    province: '湖南 · 长沙',
    region: '华中',
    elevation: 300,
    difficulty: 1,
    distance: 4,
    duration: '1-2 小时',
    scenery: 4.2,
    bestSeason: '11-12 月（枫叶）',
    tags: ['爱晚亭', '岳麓书院', '夜爬', '免费'],
    emoji: '📖',
    colors: ['#9ad0ec', '#e8f6fd', '#8bc34a', '#558b2f'],
    description: '岳麓山坐落长沙城中，山脚岳麓书院千年弦歌不绝，爱晚亭因“停车坐爱枫林晚”而得名。免费开放、交通便利，白天看枫、傍晚看日落、夜里数星星，是长沙人最日常的山。',
    tips: [
      '夜爬建议结伴并带头灯，主路有灯但支路较暗',
      '秋季爱晚亭一带枫叶正红，最佳观赏期在 12 月初',
      '山顶观景台可俯瞰橘子洲与湘江全景',
    ],
  },
  {
    id: 'baiyunshan',
    name: '白云山',
    subtitle: '广州绿肺 · 羊城第一秀',
    province: '广东 · 广州',
    region: '华南',
    elevation: 382,
    difficulty: 1,
    distance: 6,
    duration: '2-3 小时',
    scenery: 4.1,
    bestSeason: '10 月-次年 3 月',
    tags: ['城市公园', '亲子', '晨运'],
    emoji: '🌿',
    colors: ['#a5c8e8', '#eef7ff', '#6fae6f', '#3f7d4a'],
    description: '白云山是广州市区最大的自然山地公园，摩星岭为最高点。晨雾缭绕时如置身白云之间，故得此名。索道、步道与盘山公路四通八达，晨运、遛娃、看日落皆宜，老少咸宜。',
    tips: [
      '清晨登山凉快人少，是本地晨运黄金时段',
      '南门索道排队人少，可作备选',
      '摩星岭山顶广场是看日落的经典机位',
    ],
  },
  {
    id: 'qingchengshan',
    name: '青城山',
    subtitle: '青城天下幽 · 道教发源地',
    province: '四川 · 都江堰',
    region: '西南',
    elevation: 1260,
    difficulty: 2,
    distance: 8,
    duration: '3-4 小时',
    scenery: 4.5,
    bestSeason: '4-10 月',
    tags: ['道教名山', '避暑', '世界遗产'],
    emoji: '☯️',
    colors: ['#a8c8b8', '#e4f1e7', '#5f8d6e', '#39634a'],
    description: '青城山是道教发源地之一，“青城天下幽”名不虚传。前山宫观林立、香火鼎盛，后山飞泉幽谷、人少清净，与都江堰同列世界文化遗产。盛夏山间清凉，是成都人的避暑后花园。',
    tips: [
      '前山看文化、后山看风景，时间有限建议择一深度游',
      '月城湖坐船可省一段平路，带老人孩子推荐',
      '夏季多雨，出发前留意天气并备防滑鞋',
    ],
  },
  {
    id: 'lushan',
    name: '庐山',
    subtitle: '飞流直下三千尺',
    province: '江西 · 九江',
    region: '华东',
    elevation: 1474,
    difficulty: 3,
    distance: 20,
    duration: '2 天',
    scenery: 4.7,
    bestSeason: '5-9 月（避暑）',
    tags: ['瀑布', '云雾', '避暑', '云中山城'],
    emoji: '💧',
    colors: ['#9fb8c8', '#e6eef2', '#6a8f9e', '#43677a'],
    description: '庐山以云雾、瀑布与老别墅群闻名。三叠泉落差 155 米气势磅礴，含鄱口是观日出绝佳位置，牯岭镇则像一座云中山城。李白一句“飞流直下三千尺”，让庐山瀑布名传千年。',
    tips: [
      '三叠泉台阶往返较累，量力而行并留足时间',
      '山区常年多雾，备好防滑鞋和轻便雨衣',
      '观光车票按有效期售卖，按行程天数购买更划算',
    ],
  },
  {
    id: 'tianmenshan',
    name: '天门山',
    subtitle: '天门洞开 · 通天大道',
    province: '湖南 · 张家界',
    region: '华中',
    elevation: 1518,
    difficulty: 2,
    distance: 6,
    duration: '3-4 小时（含栈道）',
    scenery: 4.8,
    bestSeason: '4-6 月、9-10 月',
    tags: ['天门洞', '玻璃栈道', '索道', '999 级天梯'],
    emoji: '🚡',
    colors: ['#95a5d0', '#e0e4f5', '#7d6fb0', '#544a86'],
    description: '天门山索道全长 7455 米，堪称世界最长高山客运索道之一。999 级上天梯直通天门洞，玻璃栈道悬于千米绝壁，鬼谷栈道云雾缭绕，是张家界最震撼的城市山岳景观。',
    tips: [
      '玻璃栈道需现场购买鞋套（5 元）',
      '旺季索道排队久，建议赶早上第一批',
      '山顶气温明显低于市区，即使夏天也带件薄外套',
    ],
  },
  {
    id: 'siguniangshan',
    name: '四姑娘山大峰',
    subtitle: '5000 米级入门雪山',
    province: '四川 · 阿坝',
    region: '西南',
    elevation: 5025,
    difficulty: 5,
    distance: 16,
    duration: '3 天（含海拔适应）',
    scenery: 4.9,
    bestSeason: '5-6 月、9-10 月',
    tags: ['雪山', '冰川', '高原', '需向导'],
    emoji: '🏔️',
    colors: ['#bfe3f2', '#f4fbff', '#a8cfe0', '#7ea8c0'],
    description: '四姑娘山大峰是公认的 5000 米级入门雪山，技术要求低但海拔不低。从海子沟进山，沿途可远眺幺妹峰与冰川，凌晨冲顶看云海日出，是许多山友的人生清单第一座雪山。',
    tips: [
      '务必聘请持证向导，并预留 1-2 天适应海拔',
      '出现高反及时下撤，量力而行不逞强',
      '冰爪、头灯、羽绒、手套等装备缺一不可',
    ],
  },
  {
    id: 'hengshan_n',
    name: '恒山',
    subtitle: '北岳恒山 · 悬空奇观',
    province: '山西 · 大同',
    region: '华北',
    elevation: 2016,
    difficulty: 2,
    distance: 10,
    duration: '4-5 小时',
    scenery: 4.4,
    bestSeason: '5-10 月',
    tags: ['五岳', '悬空寺', '边塞'],
    emoji: '🕌',
    colors: ['#d9b382', '#f4e3c8', '#a8825a', '#6f5236'],
    description: '北岳恒山地处塞上，山势雄浑苍茫。山下悬空寺如浮雕嵌于翠屏峰崖壁，建成 1500 余年屹立不倒，李白醉题“壮观”二字。果老岭、姑嫂崖等景点串起道教文化与边塞风光。',
    tips: [
      '悬空寺登临需另购票且每日限流，建议提前预约',
      '大同早晚温差大，夏季也备一件外套',
      '可与云冈石窟串成一线，安排两天更从容',
    ],
  },
  {
    id: 'hengshan_s',
    name: '衡山',
    subtitle: '南岳独秀 · 香火千年',
    province: '湖南 · 衡阳',
    region: '华中',
    elevation: 1300,
    difficulty: 2,
    distance: 12,
    duration: '4-6 小时',
    scenery: 4.5,
    bestSeason: '5-10 月、12-2 月（雾凇）',
    tags: ['五岳', '祝融峰', '日出', '祈福'],
    emoji: '🕯️',
    colors: ['#98d8bb', '#e8f9f0', '#6db389', '#3f8563'],
    description: '南岳衡山以“秀”著称，祝融峰之高、藏经殿之秀、水帘洞之奇、方广寺之深并称“衡山四绝”。山上香火千年不绝，登顶祝融峰看日出云海，是湘中一带山友的经典周末。',
    tips: [
      '冬季雾凇季路面结冰，注意保暖与防滑',
      '夜爬看日出的人很多，结伴同行更安全',
      '山脚南岳大庙值得顺路一游',
    ],
  },
  {
    id: 'songshan',
    name: '嵩山',
    subtitle: '中岳嵩山 · 禅宗祖庭',
    province: '河南 · 登封',
    region: '华中',
    elevation: 1491,
    difficulty: 3,
    distance: 8,
    duration: '4-5 小时',
    scenery: 4.5,
    bestSeason: '4-6 月、9-11 月',
    tags: ['五岳', '少林寺', '三皇寨', '书卷崖'],
    emoji: '🥋',
    colors: ['#d8c8a8', '#f3ecda', '#b09b72', '#7a6a4a'],
    description: '中岳嵩山是儒释道三教荟萃之地，山脚少林寺名扬天下。三皇寨栈道悬于书卷崖之上，连天大峡谷奇峰林立；太室山峻极顶大气磅礴，嵩阳书院更添千年文脉。',
    tips: [
      '三皇寨吊桥段悬空较高，恐高者提前评估路线',
      '少林寺加塔林半天即可逛完，可与大环线组合',
      '少室山步道路面碎石多，穿抓地好的登山鞋',
    ],
  },
];

const REGIONS = ['全部', '华东', '华北', '华中', '华南', '西南', '西北'];
const DIFFS = [
  { key: '全部', label: '全部', min: 1, max: 5 },
  { key: '休闲', label: '休闲 🚶', min: 1, max: 2 },
  { key: '进阶', label: '进阶 🎒', min: 3, max: 3 },
  { key: '挑战', label: '挑战 💪', min: 4, max: 5 },
];
const DIFF_LABELS = { 1: '休闲', 2: '轻松', 3: '进阶', 4: '困难', 5: '挑战' };
const WUYUE_IDS = ['taishan', 'huashan', 'hengshan_s', 'hengshan_n', 'songshan'];
